version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysqldb 
    command: '--default-authentication-plugin=mysql_native_password'
    # healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      # interval: 3s
      # retries: 5
      # start_period: 30s    
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=psw1234
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 3306  
volumes:
  db-data:
    driver: local